version: '3'

services:
  mysql:
    image: sae51n2_mysql
    build:
      context: .
      dockerfile: mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=dolibarr
      - MYSQL_DATABASE=dolibarr_db
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dolibarr
    command: --local-infile=1
    volumes:
      - ./doli_mysql:/var/lib/mysql
    networks:
      - mynetwork

  dolibarr:
    image: sae51n2_dolibarr
    build:
      context: .
      dockerfile: dolibarr/Dockerfile
    environment:
      - DOLI_ADMIN=dolibarr
      - DOLI_ADMIN_PASSWORD=dolibarr
      - DOLI_DB_HOST=sae51n2_mysql_1
      - DOLI_DB_NAME=dolibarr_db
      - DOLI_DB_USER=dolibarr
      - DOLI_DB_PASSWORD=dolibarr
    ports:
      - "8080:80"
    networks:
      - mynetwork
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - doli_docs:/var/www/documents

networks:
  mynetwork:
    driver: bridge

volumes:
  doli_docs:
  doli_mysql: